<a href="https://colab.research.google.com/github/Carrasco757/StreamLit/blob/main/score_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instalando bibliotecas e verificando o Dataset
Carrega pacotes

In [1]:
## Importa pacotes
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import pandas as pd
import statsmodels.formula.api as smf
from IPython.display import Image

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [5]:
df = pd.read_csv('/content/DadosEmpresaXYZ.csv')

df.drop(labels=['navegador', 'marca_dispositivo', 'modelo_de_dispositivo', 'mensagem_estado', 'sessão_data_hora', 'login_google', 'login_facebook', 'login_senha'], axis=1, inplace=True )
df.head()

     estado receita  ... score_debito score_consumidor_positivo
0  approved     NÃO  ...          NaN                       NaN
1  rejected     NÃO  ...          NaN                       NaN
2  rejected     NÃO  ...          NaN                       NaN
3  rejected     NÃO  ...          NaN                       NaN
4  rejected     NÃO  ...          NaN                       NaN

[5 rows x 23 columns]

In [6]:
df.dropna(axis=0, inplace=True)

In [7]:
df.head()

        estado receita  ... score_debito score_consumidor_positivo
385   approved     NÃO  ...          NÃO                       SIM
2696  approved     NÃO  ...          NÃO                       SIM
3857  approved     NÃO  ...          NÃO                       SIM
4516  approved     NÃO  ...          NÃO                       SIM
6261  approved     NÃO  ...          SIM                       SIM

[5 rows x 23 columns]